Update checking of grandparent items
When using Middleman's Localization features the grandparent check fails when an object is null. This change fixes that issue and allows PageGroups and Localization to work together.

Previous error that was being raised:
/Users/markor/git/middleman-pagegroups-1.0.6/lib/middleman-pagegroups/extension.rb:423:in `block in manipulate_resource_list': undefined method `parent' for nil:NilClass (NoMethodError)

With this change that error no longer appears and the pages build as expected.